services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [ 5672, 15672 ]

  mailcatcher:
    image: schickling/mailcatcher
    ports: [ 1025, 1080 ]

  blackfire:
    image: blackfire/blackfire
    env_file: .env.local
    ports: [ 8707 ]
